import { ComingSoon } from "@/components/ui/ComingSoon";

export default function MediaPage() {
  return (
    <ComingSoon
      eyebrow="Media library"
      title="Images & video, ready for any screen"
      milestone="M2"
      body="Upload directly to Supabase Storage via signed URLs. Videos transcode through Mux and serve as MP4 for offline player caching. Images get thumbnails generated by sharp."
    />
  );
}
